services:
  db:
    image: postgres:15
    container_name: health-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: health-redis
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: health-backend
    command: python manage.py runserver 0.0.0.0:8090
    volumes:
      - .:/app
    ports:
      - "8090:8090"
    depends_on:
      - db
      - redis
    env_file:
      - .env

  celery:
    build: .
    container_name: health-celery
    command: celery -A healthcare_backend worker -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      - .env

volumes:
  postgres_data:
