# Generated by Django 5.2.6 on 2025-09-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_category_post_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('uses', models.TextField()),
                ('dosage', models.CharField(max_length=255)),
                ('confidence', models.FloatField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
