# Generated by Django 5.2.6 on 2025-09-20 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_extractedmedicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.appointment'),
        ),
    ]
